Acceptance test done and unit tests updated
sjtuckerUWM/Ta_App_Vikings_Creed pull request #73
Opened 2022-05-15 16:48 UTC by JPeterson9

Section acceptance test added and all unit tests can now be run as a directory. All unit tests now pass as well

2022-05-15 19:17 UTC, turkogl3 approved these changes

2022-05-15 23:16 UTC, miladmasoodi approved these changes
So I approved to update the names but the add_section acceptance tests and several other acceptance tests aren't testing anything other than the database and need to be changed

2022-05-16 16:35 UTC, vitky25 approved these changes

2022-05-16 22:33 UTC, miladmasoodi requested changes

2022-05-16 22:33 UTC, miladmasoodi commented on acceptance_tests/test_Add_Section.py
> +        resp = self.client.post(f'/addSection/', {'id': -3}, follow=True)
not a valid url needs id number and another slash and the actual inputs

2022-05-16 22:33 UTC, miladmasoodi commented on acceptance_tests/test_Add_Section.py
> +        self.section2 = SectionModel.objects.create(course_id=3, section_id=901)
shouldnt add with the database, it should update from the self.client.post(~~~~~)

2022-05-16 22:33 UTC, miladmasoodi commented on acceptance_tests/test_Add_Section.py
> +        resp = self.client.post(f'/addSection/{self.section2.section_id}', {'id': self.section2.section_id})
the id in the url should be the course's id,

2022-05-16 22:54 UTC, merged